# Generated by Django 4.0.3 on 2022-05-29 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comapny_name', models.CharField(max_length=150)),
                ('vendor_name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField(default='0')),
                ('Price', models.IntegerField(default='0')),
                ('Receive_Quantity', models.IntegerField(default='0')),
                ('Receive_By', models.CharField(max_length=50)),
                ('Issue_Quantity', models.IntegerField(default='0')),
                ('Phone_Number', models.CharField(max_length=50)),
                ('Created_By', models.CharField(max_length=50)),
                ('Reorder_Level', models.IntegerField(default='0')),
                ('Last_Updated', models.DateTimeField()),
                ('Issue_By', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Issue_To', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_module.vendor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_module.category')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField(default='0')),
                ('Price', models.IntegerField(default='0')),
                ('Receive_Quantity', models.IntegerField(default='0')),
                ('Receive_By', models.CharField(max_length=50)),
                ('Issue_Quantity', models.IntegerField(default='0')),
                ('Phone_Number', models.CharField(max_length=50)),
                ('Created_By', models.CharField(max_length=50)),
                ('Reorder_Level', models.IntegerField(default='0')),
                ('Last_Updated', models.DateTimeField(auto_now=True)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Issue_By', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Issue_To', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_module.vendor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_module.category')),
            ],
        ),
    ]
