# Generated by Django 4.0.3 on 2022-06-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_module', '0002_alter_stock_phone_number_alter_vendor_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='state',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
