# Generated by Django 4.0.3 on 2022-06-14 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('designation', models.CharField(default='', max_length=200, null=True)),
                ('salary', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=50, null=True)),
                ('mobile', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('dob', models.DateTimeField(null=True)),
                ('joined_on', models.DateTimeField(null=True)),
                ('address', models.TextField(default='', null=True)),
                ('city', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Khulna', 'Khulna'), ('Sylhet', 'Sylhet'), ('Rajshahi', 'Rajshahi'), ('Mymensingh', 'Mymensingh'), ('Barisal', 'Barisal'), ('Rangpur', 'Rangpur'), ('Comilla', 'Comilla'), ('Narayanganj', 'Narayanganj'), ('Gazipur', 'Gazipur'), ('Feni', 'Feni'), ('Cox Bazar', 'Cox Bazar')], default='', max_length=50, null=True)),
                ('department', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm_module.department')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
